# Generated by Django 3.1.3 on 2020-11-12 01:39

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='State',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('current_state', models.CharField(max_length=15)),
                ('question', models.CharField(max_length=100)),
                ('choices', django.contrib.postgres.fields.ArrayField(base_field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=100), size=None), size=None)),
                ('correct_choice', models.CharField(max_length=100)),
                ('time_stamp', models.DateTimeField()),
            ],
        ),
    ]
