# Generated by Django 3.1.3 on 2020-11-16 18:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0005_auto_20201116_1749'),
        ('main_app', '0004_result_answer'),
    ]

    operations = [
    ]
