# Generated by Django 3.1.3 on 2020-11-17 16:10

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0006_merge_20201116_1820'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='remove_order',
            field=django.contrib.postgres.fields.ArrayField(base_field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=100), size=None), default=['1', '2'], size=None),
            preserve_default=False,
        ),
    ]
