# Generated by Django 3.1.1 on 2020-11-17 03:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0006_merge_20201116_1820'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='quip',
            field=models.CharField(default='play to win', max_length=100),
        ),
    ]
