# Generated by Django 3.1.1 on 2020-11-17 16:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0008_profile_url'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Photo',
        ),
    ]
