# Generated by Django 3.1.1 on 2020-11-17 17:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0009_delete_photo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='url',
            field=models.CharField(default='https://www.minervastrategies.com/wp-content/uploads/2016/03/default-avatar.jpg', max_length=200),
        ),
    ]
