# Generated by Django 3.1.3 on 2020-11-17 17:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0007_question_remove_order'),
        ('main_app', '0010_auto_20201117_1701'),
    ]

    operations = [
    ]
