# Generated by Django 3.1.1 on 2020-11-18 19:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0012_auto_20201118_1850'),
        ('main_app', '0012_auto_20201118_1916'),
    ]

    operations = [
    ]
