# Generated by Django 3.1.3 on 2020-11-18 20:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0013_auto_20201118_1956'),
        ('main_app', '0014_auto_20201118_2000'),
    ]

    operations = [
    ]
